# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Institute for Research and Innovation in Software for High Energy Physics
email: Peter.Elmer@cern.ch
description: >- # this means to ignore newlines until "baseurl:"
  The Institute for Research and Innovation in Software for High Energy Physics (IRIS-HEP) has been established to meet the software and computing challenges of the planned upgrades to the Large Hadron Collider, the world's most powerful particle accelerator.  IRIS-HEP pursues R&D for the software needed to acquire, manage, process and analyze the torrent of data that will be produced by the upgrade accelerator and its detectors as part of the search for discoveries beyond the Standard Model of Particle Physics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iris-hep.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iris_hep
github_username:  iris-hep
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache

strict_front_matter: true

liquid:
  error_mode: strict
  strict_filters: true

# Exclude from processing.
exclude:
  - _cache
  - _scripts
  - bin
  - .github
  - Rakefile

sass:
  sass_dir: _sass

indico:
  url: https://indico.cern.ch
  cache-command: bundle exec rake cache
  ids:
    topical: 10570
    nsfreport: 11204
    blueprint: 11329
    sb: 10989
    ap: 11519

inspire:
  cache-dir: _cache
  pub-dir: publications
  authors:
    min-len: 10
    trunc-len: 1

iris-hep:
  extra-focus-areas:
    - core
  projectless-focus-areas:
    - core
    - ssc
    - blueprint
    - ssl
