name: CI

on:
  pull_request:
  push:
    branches: master

jobs:
  website:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Prepare to build site
      uses: ./.github/actions/prepare-build-site

    - name: Check RuboCop
      shell: bash
      run: bundle exec rake rubocop

    - name: Build the site
      shell: bash
      run: bundle exec rake build
      env:
        JEKYLL_ENV: production
        INDICO_API_KEY: ${{ secrets.INDICO_API_KEY }}
        INDICO_SECRET_KEY: ${{ secrets.INDICO_SECRET_KEY }}
